#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if xrandr -q | grep 'HDMI2 connected'; then
  xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI2 --mode 1920x1080 --rotate normal --right-of eDP1
  bspc monitor eDP1 -d I II III IV V
  bspc monitor HDMI2 -d VI VII VIII IX X
else
  bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
fi


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Border Colors
bspc config active_border_color \#14536C
bspc config focused_border_color \#14536C
bspc config normal_border_color \#052F3F
# Change keyboard layout
setxkbmap -model pc104 -layout us,ua -variant ,, -option grp:win_space_toggle

# Change Background
feh --bg-fill ~/.dotfiles/backgrounds/red_cyan_futuristic.png

# Launch Polybar
bash ~/.config/polybar/launch.sh

# Launch Picom
picom -I 0.1 -O 0.1
