#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if xrandr -q | grep 'HDMI1 connected'; then
  xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI1 --mode 1920x1080 --rotate normal --right-of eDP1
  bspc monitor eDP1 -d I II III IV V
  bspc monitor HDMI1 -d VI VII VIII IX X
elif xrandr -q | grep 'HDMI2 connected'; then
  xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI2 --mode 1920x1080 --rotate normal --right-of eDP1
  bspc monitor eDP1 -d I II III IV V
  bspc monitor HDMI2 -d VI VII VIII IX X
else
  bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
fi

# Pointer Settings
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a Godot desktop='^3'
bspc rule -a Slack desktop='^5'

# Border Colors
bspc config active_border_color \#14536C
bspc config focused_border_color \#14536C
bspc config normal_border_color \#052F3F

# Change keyboard layout
setxkbmap -model pc104 -layout us,ua -variant ,, -option grp:win_space_toggle

# Change Background
feh --bg-fill ~/.dotfiles/backgrounds/red_cyan_futuristic.png

# Launch Polybar
bash ~/.config/polybar/launch.sh

# Launch Picom
picom -I 0.1 -O 0.1 &

# Notification Service
dunst &

# For Java apps
wmname LG3D

# Make custom cursor be visible everywhere
xsetroot -cursor_name left_ptr

# Startup Sound
mpv --no-video ~/.dotfiles/startup_sounds/startup_sound.mp3
